%CTF: 1.00
%FileType: WVMD WVM9 "Wave History"
%UUID: EB47AA1B-4837-4C39-A172-55FE1F086D0E
%Manufacturer: CODAR Ocean Sensors. SeaSonde
%Site: PBCN ""
%TimeMarks: start
%TimeStamp: 2026 09 01  00 00 00
%TimeZone: "UTC" +0.000 0
%Origin:  41.3475833    2.1740500
%%
%%
%% Note: Parameters for Last processed item...
%TimeCoverage: 0.250 hours
%AntennaBearing: 177.0
%RangeCells: 31
%DopplerCells: 512
%TransmitCenterFreqMHz: 13.500000
%TransmitBandwidthKHz: -90.068695
%TransmitSweepRateHz: 2.000000
%CoastlineSector: 50.0 190.0  %% Start CW to Stop in Deg NCW
%CurrentVelocityLimit: 180
%BraggSmoothingPoints: 5
%BraggHasSecondOrder: 1
%WaveBraggNoiseThreshold: 1.6
%WaveBraggPeakDropOff: 100.0
%WaveBraggPeakNull: 10.0
%WaveSplitBraggRatio: 6.30
%MaximumWavePeriod: 17.0
%WaveBearingLimits: 104.0 296.0  %% Start CW to Stop in Deg NCW
%WaveUseInnerBragg: 0  %% 0 No, 1 Yes
%WaveSecondOrderMethod: 1   %% 0/1 OnShore, 2 OffShore
%WaveSaturationRatio: 0.80
%WaveHeightLimit: 20.0
%WavePeriodSetLimit: 10.0
%PatternUUID: PatternUUID
%WaveMergeMethod: 1  %% 0 None, 1 Average, 2 Median, 3 Outlier
%WaveReductionMethod: 3  %% 0 None, 1=Temporal, 2=Spatial, 3=Both
%WaveMinDopplerPoints: 10
%WaveMinVectors: 1
%WaveMaximumWaveHeight: 1.0
%WaveMaximumWavePeriodChange: 7.00
%%
%TableType: WAVL WVM9
%TableColumns: 22
%TableColumnTypes: TIME MWHT MWPD WAVB WNDB PMWH ACNT DIST RCLL LOND LATD WDPT MTHD FLAG WHNM WHSD TYRS TMON TDAY THRS TMIN TSEC 
%TableRows: 21
%TableStart:
%%     Time     ----------Wave----------    Wind    WaveNF                                  Placement   Placement                                Height    Height                        
%%   FromStart   Height  Period   From      From    Height   Spectra   Distance   Range     Longitude    Latitude   Doppler    Wave    Vector    Valid      StdDv    Time                
%%   (seconds)     (m)     (s)   (True)    (True)     (m)     count      (km)      cell       (deg)       (deg)       bins    Method    Flag     points      (m)     Year Mo Dy  Hr Mn  S
             0    999.00 999.00     0.0    135.9      0.56      168        nan        2      0.0000000   0.0000000       7        2      240           0     0.00    2026 09 01  00 00 00
           600    999.00 999.00     0.0    135.3      0.55      168        nan        2      0.0000000   0.0000000       7        2      112           0     0.00    2026 09 01  00 10 00
          1200    999.00 999.00     0.0    134.8      0.53      168        nan        2      0.0000000   0.0000000       7        2      112           0     0.00    2026 09 01  00 20 00
          1800    999.00 999.00     0.0    135.2      0.53      168        nan        2      0.0000000   0.0000000       7        2      112           0     0.00    2026 09 01  00 30 00
          2400    999.00 999.00     0.0    137.3      0.52      168        nan        2      0.0000000   0.0000000       7        2      112           0     0.00    2026 09 01  00 40 00
          3000      4.68   7.00   287.0    157.0      0.79      168        nan       20      0.0000000   0.0000000      10        2        0           1     0.00    2026 09 01  00 50 00
          3600      4.68   7.00   287.0    157.0      0.79      168        nan       20      0.0000000   0.0000000      10        2        0           1     0.00    2026 09 01  01 00 00
          4200      4.68   7.00   287.0    157.0      0.79      168        nan       20      0.0000000   0.0000000      10        2        0           1     0.00    2026 09 01  01 10 00
          4800      4.68   7.00   287.0    157.0      0.79      168        nan       20      0.0000000   0.0000000      10        2        0           1     0.00    2026 09 01  01 20 00
          5400    999.00 999.00     0.0    143.5      0.53      168        nan        2      0.0000000   0.0000000       7        2      240           0     0.00    2026 09 01  01 30 00
          6000    999.00 999.00     0.0    144.4      0.53      168        nan        2      0.0000000   0.0000000       7        2      240           0     0.00    2026 09 01  01 40 00
          6600    999.00 999.00     0.0    144.0      0.53      168        nan        2      0.0000000   0.0000000       7        2      240           0     0.00    2026 09 01  01 50 00
          7200    999.00 999.00     0.0    142.4      0.54      168        nan        2      0.0000000   0.0000000       6        2      112           0     0.00    2026 09 01  02 00 00
          7800      4.16   5.00   292.0     97.0      0.62      168        nan       12      0.0000000   0.0000000      14        2        0           1     0.00    2026 09 01  02 10 00
          8400      4.16   5.00   292.0     97.0      0.62      168        nan       12      0.0000000   0.0000000      14        2        0           1     0.00    2026 09 01  02 20 00
          9000      4.16   5.00   292.0     97.0      0.62      168        nan       12      0.0000000   0.0000000      14        2        0           1     0.00    2026 09 01  02 30 00
          9600    999.00 999.00     0.0    144.0      0.64      168        nan        2      0.0000000   0.0000000       4        2      240           0     0.00    2026 09 01  02 40 00
         10200      4.49   6.00   292.0    147.0      0.72      168        nan       13      0.0000000   0.0000000      11        2        0           1     0.00    2026 09 01  02 50 00
         10800      4.34   6.00   292.0    137.0      0.61      168        nan       13      0.0000000   0.0000000      11        2        0           2     0.15    2026 09 01  03 00 00
         11400      4.34   6.00   292.0    137.0      0.61      168        nan       13      0.0000000   0.0000000      11        2        0           2     0.15    2026 09 01  03 10 00
         12000      4.34   6.00   292.0    137.0      0.61      168        nan       13            nan         nan      11        2        0           2     0.15    2026 09 01  03 20 00
%TableEnd:
%%
%%
%ProcessedTimeStamp: 2026 09 01  03 59 26
%ProcessingTool: "WaveModelFilter" 4.0.4
%ProcessingTool: "SpectraToWavesModel" 11.10.0
%ProcessingTool: "WaveModelForFive" 11.8.0
%ProcessingTool: "WaveModelArchiver" 13.2.1
%ProcessingTool: "AnalyzeSpectra" 12.0.0
%End:
