%CTF: 1.00
%FileType: WVMD WVM9 "Wave History"
%UUID: 01D76200-4C34-4CFD-AC40-8B9EF02DA885
%Manufacturer: CODAR Ocean Sensors. SeaSonde
%Site: PBCN ""
%TimeMarks: start
%TimeStamp: 2024 09 01  00 00 00
%TimeZone: "UTC" +0.000 0
%Origin:  41.3475833    2.1740500
%%
%%
%% Note: Parameters for Last processed item...
%TimeCoverage: 0.250 hours
%AntennaBearing: 177.0
%RangeCells: 31
%DopplerCells: 512
%TransmitCenterFreqMHz: 13.500000
%TransmitBandwidthKHz: -90.068695
%TransmitSweepRateHz: 2.000000
%CoastlineSector: 50.0 190.0  %% Start CW to Stop in Deg NCW
%CurrentVelocityLimit: 180
%BraggSmoothingPoints: 5
%BraggHasSecondOrder: 1
%WaveBraggNoiseThreshold: 1.6
%WaveBraggPeakDropOff: 100.0
%WaveBraggPeakNull: 10.0
%WaveSplitBraggRatio: 6.30
%MaximumWavePeriod: 17.0
%WaveBearingLimits: 104.0 296.0  %% Start CW to Stop in Deg NCW
%WaveUseInnerBragg: 0  %% 0 No, 1 Yes
%WaveSecondOrderMethod: 1   %% 0/1 OnShore, 2 OffShore
%WaveSaturationRatio: 0.80
%WaveHeightLimit: 20.0
%WavePeriodSetLimit: 10.0
%PatternUUID: PatternUUID
%WaveMergeMethod: 1  %% 0 None, 1 Average, 2 Median, 3 Outlier
%WaveReductionMethod: 3  %% 0 None, 1=Temporal, 2=Spatial, 3=Both
%WaveMinDopplerPoints: 10
%WaveMinVectors: 1
%WaveMaximumWaveHeight: 1.0
%WaveMaximumWavePeriodChange: 7.00
%%
%TableType: WAVL WVM9
%TableColumns: 22
%TableColumnTypes: TIME MWHT MWPD WAVB WNDB PMWH ACNT DIST RCLL LOND LATD WDPT MTHD FLAG WHNM WHSD TYRS TMON TDAY THRS TMIN TSEC 
%TableRows: 20
%TableStart:
%%     Time     ----------Wave----------    Wind    WaveNF                                  Placement   Placement                                Height    Height                        
%%   FromStart   Height  Period   From      From    Height   Spectra   Distance   Range     Longitude    Latitude   Doppler    Wave    Vector    Valid      StdDv    Time                
%%   (seconds)     (m)     (s)   (True)    (True)     (m)     count      (km)      cell       (deg)       (deg)       bins    Method    Flag     points      (m)     Year Mo Dy  Hr Mn  S
             0      1.86   6.25   292.0    159.5      0.29      168        nan        6      0.0000000   0.0000000      15        2        0           4     0.04    2024 09 01  00 00 00
           600      1.84   6.00   292.0    157.0      0.28      168        nan        6      0.0000000   0.0000000      13        2        0           4     0.05    2024 09 01  00 10 00
          1200      1.82   6.00   292.0    155.0      0.27      168        nan        6      0.0000000   0.0000000      12        2        0           5     0.05    2024 09 01  00 20 00
          1800      1.85   5.83   292.0    153.7      0.27      168        nan        6      0.0000000   0.0000000      12        2        0           6     0.07    2024 09 01  00 30 00
          2400      1.83   5.75   292.0    148.3      0.27      168        nan        7      0.0000000   0.0000000      12        2        0           8     0.10    2024 09 01  00 40 00
          3000      1.83   5.75   292.0    148.3      0.27      168        nan        7      0.0000000   0.0000000      12        2        0           8     0.10    2024 09 01  00 50 00
          3600      1.84   5.75   292.0    148.3      0.27      168        nan        7      0.0000000   0.0000000      13        2        0           8     0.10    2024 09 01  01 00 00
          4200      1.82   5.55   292.0    149.7      0.27      168        nan       12      0.0000000   0.0000000      13        2        0          11     0.09    2024 09 01  01 10 00
          4800      1.82   5.50   291.5    145.0      0.27      168        nan       12      0.0000000   0.0000000      13        2        0          10     0.10    2024 09 01  01 20 00
          5400      1.82   5.44   291.4    144.8      0.28      168        nan       12      0.0000000   0.0000000      13        2        0           9     0.10    2024 09 01  01 30 00
          6000      1.81   5.50   291.5    146.0      0.27      168        nan       12      0.0000000   0.0000000      14        2        0          10     0.09    2024 09 01  01 40 00
          6600      1.81   5.43   291.3    148.4      0.26      168        nan       12      0.0000000   0.0000000      15        2        0           7     0.07    2024 09 01  01 50 00
          7200      1.82   5.60   291.0    149.0      0.27      168        nan       12      0.0000000   0.0000000      14        2        0          10     0.07    2024 09 01  02 00 00
          7800      1.79   5.75   291.4    151.4      0.25      168        nan       12      0.0000000   0.0000000      15        2        0          16     0.11    2024 09 01  02 10 00
          8400      1.74   5.94   291.1    148.3      0.25      168        nan       10      0.0000000   0.0000000      15        2        0          16     0.13    2024 09 01  02 20 00
          9000      1.72   6.06   291.1    148.9      0.25      168        nan       10      0.0000000   0.0000000      15        2        0          16     0.12    2024 09 01  02 30 00
          9600      1.69   6.07   290.9    148.4      0.25      168        nan       10      0.0000000   0.0000000      15        2        0          14     0.10    2024 09 01  02 40 00
         10200      1.67   6.14   290.9    149.1      0.24      168        nan       10      0.0000000   0.0000000      15        2        0          14     0.12    2024 09 01  02 50 00
         10800      1.62   6.00   291.0    150.0      0.24      168        nan       10      0.0000000   0.0000000      15        2        0          10     0.10    2024 09 01  03 00 00
         11400      1.61   6.00   291.4    150.3      0.24      168        nan       10            nan         nan      15        2        0           9     0.10    2024 09 01  03 10 00
%TableEnd:
%%
%%
%ProcessedTimeStamp: 2024 09 01  03 48 16
%ProcessingTool: "WaveModelFilter" 4.0.4
%ProcessingTool: "SpectraToWavesModel" 11.10.0
%ProcessingTool: "WaveModelForFive" 11.8.0
%ProcessingTool: "WaveModelArchiver" 13.2.1
%ProcessingTool: "AnalyzeSpectra" 12.0.0
%End:
