%CTF: 1.00
%FileType: WVMD WVM9 "Wave History"
%UUID: 000B537A-BD49-4315-BCA9-424E85E714B4
%Manufacturer: CODAR Ocean Sensors. SeaSonde
%Site: PBCN ""
%TimeMarks: start
%TimeStamp: 2026 08 01  00 00 00
%TimeZone: "UTC" +0.000 0
%Origin:  41.3475833    2.1740500
%%
%%
%% Note: Parameters for Last processed item...
%TimeCoverage: 0.250 hours
%AntennaBearing: 177.0
%RangeCells: 31
%DopplerCells: 512
%TransmitCenterFreqMHz: 13.500000
%TransmitBandwidthKHz: -90.068695
%TransmitSweepRateHz: 2.000000
%CoastlineSector: 50.0 190.0  %% Start CW to Stop in Deg NCW
%CurrentVelocityLimit: 180
%BraggSmoothingPoints: 5
%BraggHasSecondOrder: 1
%WaveBraggNoiseThreshold: 1.6
%WaveBraggPeakDropOff: 100.0
%WaveBraggPeakNull: 10.0
%WaveSplitBraggRatio: 6.30
%MaximumWavePeriod: 17.0
%WaveBearingLimits: 104.0 296.0  %% Start CW to Stop in Deg NCW
%WaveUseInnerBragg: 0  %% 0 No, 1 Yes
%WaveSecondOrderMethod: 1   %% 0/1 OnShore, 2 OffShore
%WaveSaturationRatio: 0.80
%WaveHeightLimit: 20.0
%WavePeriodSetLimit: 10.0
%PatternUUID: PatternUUID
%WaveMergeMethod: 1  %% 0 None, 1 Average, 2 Median, 3 Outlier
%WaveReductionMethod: 3  %% 0 None, 1=Temporal, 2=Spatial, 3=Both
%WaveMinDopplerPoints: 10
%WaveMinVectors: 1
%WaveMaximumWaveHeight: 1.0
%WaveMaximumWavePeriodChange: 7.00
%%
%TableType: WAVL WVM9
%TableColumns: 22
%TableColumnTypes: TIME MWHT MWPD WAVB WNDB PMWH ACNT DIST RCLL LOND LATD WDPT MTHD FLAG WHNM WHSD TYRS TMON TDAY THRS TMIN TSEC 
%TableRows: 19
%TableStart:
%%     Time     ----------Wave----------    Wind    WaveNF                                  Placement   Placement                                Height    Height                        
%%   FromStart   Height  Period   From      From    Height   Spectra   Distance   Range     Longitude    Latitude   Doppler    Wave    Vector    Valid      StdDv    Time                
%%   (seconds)     (m)     (s)   (True)    (True)     (m)     count      (km)      cell       (deg)       (deg)       bins    Method    Flag     points      (m)     Year Mo Dy  Hr Mn  S
             0      5.58   9.00   152.0    297.0      1.29      144        nan       14      0.0000000   0.0000000      10        2        0           1     0.00    2026 08 01  00 00 00
           600    999.00 999.00     0.0    246.7      1.39      144        nan        2      0.0000000   0.0000000       5        2      240           0     0.00    2026 08 01  00 10 00
          1200      5.50   9.50   219.5    237.0      1.17      144        nan       14      0.0000000   0.0000000      11        2        0           2     0.08    2026 08 01  00 20 00
          1800      5.50   9.75   250.6    194.1      1.18      168        nan       19      0.0000000   0.0000000      12        2        0           4     0.11    2026 08 01  00 30 00
          2400      5.47  10.00   270.3    173.8      1.15      168        nan       19      0.0000000   0.0000000      13        2        0           3     0.11    2026 08 01  00 40 00
          3000      5.38  10.20   261.9    180.8      1.13      168        nan       19      0.0000000   0.0000000      14        2        0           5     0.14    2026 08 01  00 50 00
          3600      5.32  10.25   261.9    194.1      1.11      168        nan       13      0.0000000   0.0000000      14        2        0           4     0.08    2026 08 01  01 00 00
          4200      5.32  10.25   261.9    194.1      1.11      168        nan       13      0.0000000   0.0000000      14        2        0           4     0.08    2026 08 01  01 10 00
          4800      5.32  10.25   261.9    194.1      1.11      168        nan       13      0.0000000   0.0000000      14        2        0           4     0.08    2026 08 01  01 20 00
          5400      5.24  10.50   249.5    222.0      1.10      168        nan       13      0.0000000   0.0000000      16        2        0           2     0.00    2026 08 01  01 30 00
          6000      5.24  10.00   257.0    147.0      1.04      168        nan        2      0.0000000   0.0000000      15        2        0           1     0.00    2026 08 01  01 40 00
          6600      5.24  10.00   257.0    147.0      1.04      168        nan        2      0.0000000   0.0000000      15        2        0           1     0.00    2026 08 01  01 50 00
          7200    999.00 999.00     0.0    151.0      1.21      168        nan        2      0.0000000   0.0000000       5        2      240           0     0.00    2026 08 01  02 00 00
          7800    999.00 999.00     0.0    140.9      1.09      168        nan        2      0.0000000   0.0000000       6        2      240           0     0.00    2026 08 01  02 10 00
          8400    999.00 999.00     0.0    137.6      1.04      168        nan        2      0.0000000   0.0000000       5        2      240           0     0.00    2026 08 01  02 20 00
          9000      5.57   6.00   292.0    137.0      0.81      168        nan        9      0.0000000   0.0000000      12        2        0           1     0.00    2026 08 01  02 30 00
          9600      5.56   5.50   284.5    112.0      0.81      168        nan       16      0.0000000   0.0000000      13        2        0           2     0.02    2026 08 01  02 40 00
         10200      5.56   5.50   284.5    112.0      0.81      168        nan       16      0.0000000   0.0000000      13        2        0           2     0.02    2026 08 01  02 50 00
         10800      5.54   5.00   277.0     87.0      0.81      168        nan       16            nan         nan      13        2        0           1     0.00    2026 08 01  03 00 00
%TableEnd:
%%
%%
%ProcessedTimeStamp: 2026 08 01  03 39 43
%ProcessingTool: "WaveModelFilter" 4.0.4
%ProcessingTool: "SpectraToWavesModel" 11.10.0
%ProcessingTool: "WaveModelForFive" 11.8.0
%ProcessingTool: "WaveModelArchiver" 13.2.1
%ProcessingTool: "AnalyzeSpectra" 12.0.0
%End:
