%CTF: 1.00
%FileType: WVMD WVM9 "Wave History"
%UUID: E1D7CD1E-4576-4E03-A2B7-DB0DFC24CC8E
%Manufacturer: CODAR Ocean Sensors. SeaSonde
%Site: GNST ""
%TimeMarks: start
%TimeStamp: 2026 09 01  00 00 00
%TimeZone: "UTC" +0.000 0
%Origin:  41.2560667    1.9221833
%%
%%
%% Note: Parameters for Last processed item...
%TimeCoverage: 0.250 hours
%AntennaBearing: 208.0
%RangeCells: 31
%DopplerCells: 512
%TransmitCenterFreqMHz: 13.500000
%TransmitBandwidthKHz: -90.068695
%TransmitSweepRateHz: 2.000000
%CoastlineSector: 82.0 250.0  %% Start CW to Stop in Deg NCW
%CurrentVelocityLimit: 180
%BraggSmoothingPoints: 4
%BraggHasSecondOrder: 1
%WaveBraggNoiseThreshold: 3.2
%WaveBraggPeakDropOff: 100.0
%WaveBraggPeakNull: 10.0
%WaveSplitBraggRatio: 6.30
%MaximumWavePeriod: 17.0
%WaveBearingLimits: 116.0 284.0  %% Start CW to Stop in Deg NCW
%WaveUseInnerBragg: 0  %% 0 No, 1 Yes
%WaveSecondOrderMethod: 1   %% 0/1 OnShore, 2 OffShore
%WaveSaturationRatio: 0.80
%WaveHeightLimit: 20.0
%WavePeriodSetLimit: 10.0
%PatternUUID: PatternUUID
%WaveMergeMethod: 1  %% 0 None, 1 Average, 2 Median, 3 Outlier
%WaveReductionMethod: 3  %% 0 None, 1=Temporal, 2=Spatial, 3=Both
%WaveMinDopplerPoints: 10
%WaveMinVectors: 1
%WaveMaximumWaveHeight: 1.0
%WaveMaximumWavePeriodChange: 7.00
%%
%TableType: WAVL WVM9
%TableColumns: 22
%TableColumnTypes: TIME MWHT MWPD WAVB WNDB PMWH ACNT DIST RCLL LOND LATD WDPT MTHD FLAG WHNM WHSD TYRS TMON TDAY THRS TMIN TSEC 
%TableRows: 20
%TableStart:
%%     Time     ----------Wave----------    Wind    WaveNF                                  Placement   Placement                                Height    Height                        
%%   FromStart   Height  Period   From      From    Height   Spectra   Distance   Range     Longitude    Latitude   Doppler    Wave    Vector    Valid      StdDv    Time                
%%   (seconds)     (m)     (s)   (True)    (True)     (m)     count      (km)      cell       (deg)       (deg)       bins    Method    Flag     points      (m)     Year Mo Dy  Hr Mn  S
             0      0.79   6.52   282.3    120.6      0.08      168        nan       23      0.0000000   0.0000000      18        2        0          23     0.09    2026 09 01  00 00 00
           600      0.78   6.50   283.0    119.7      0.07      168        nan       15      0.0000000   0.0000000      19        2        0          24     0.09    2026 09 01  00 10 00
          1200      0.76   6.42   283.0    119.9      0.07      168        nan       14      0.0000000   0.0000000      20        2        0          26     0.08    2026 09 01  00 20 00
          1800      0.75   6.38   283.0    119.4      0.06      168        nan       13      0.0000000   0.0000000      20        2        0          21     0.08    2026 09 01  00 30 00
          2400      0.77   6.33   283.0    120.9      0.06      168        nan       13      0.0000000   0.0000000      20        2        0          21     0.08    2026 09 01  00 40 00
          3000      0.77   6.36   283.0    121.6      0.06      168        nan       13      0.0000000   0.0000000      20        2        0          22     0.08    2026 09 01  00 50 00
          3600      0.77   6.38   283.0    121.8      0.06      168        nan       13      0.0000000   0.0000000      20        2        0          21     0.08    2026 09 01  01 00 00
          4200      0.77   6.42   283.0    122.7      0.06      168        nan       13      0.0000000   0.0000000      20        2        0          19     0.08    2026 09 01  01 10 00
          4800      0.78   6.29   283.0    125.1      0.06      168        nan       12      0.0000000   0.0000000      20        2        0          17     0.08    2026 09 01  01 20 00
          5400      0.80   6.31   283.0    126.5      0.06      168        nan       12      0.0000000   0.0000000      19        2        0          13     0.06    2026 09 01  01 30 00
          6000      0.84   6.33   283.0    125.3      0.07      168        nan       12      0.0000000   0.0000000      19        2        0          15     0.07    2026 09 01  01 40 00
          6600      0.86   6.31   283.0    124.2      0.07      168        nan       12      0.0000000   0.0000000      19        2        0          13     0.09    2026 09 01  01 50 00
          7200      0.89   6.17   283.0    124.7      0.07      168        nan       13      0.0000000   0.0000000      19        2        0          12     0.08    2026 09 01  02 00 00
          7800      0.93   6.14   283.0    125.1      0.07      168        nan       13      0.0000000   0.0000000      19        2        0          14     0.10    2026 09 01  02 10 00
          8400      0.91   5.83   283.0    125.1      0.07      168        nan       13      0.0000000   0.0000000      19        2        0          24     0.10    2026 09 01  02 20 00
          9000      0.93   5.70   283.0    125.0      0.07      168        nan       13      0.0000000   0.0000000      19        2        0          20     0.10    2026 09 01  02 30 00
          9600      0.94   5.76   283.0    124.7      0.06      168        nan       13      0.0000000   0.0000000      19        2        0          21     0.09    2026 09 01  02 40 00
         10200      0.93   5.78   283.0    125.2      0.06      168        nan       12      0.0000000   0.0000000      19        2        0          18     0.09    2026 09 01  02 50 00
         10800      0.92   5.81   283.0    125.5      0.06      168        nan       12      0.0000000   0.0000000      19        2        0          16     0.10    2026 09 01  03 00 00
         11400      0.91   5.87   283.0    125.3      0.06      168        nan       12            nan         nan      19        2        0          15     0.09    2026 09 01  03 10 00
%TableEnd:
%%
%%
%ProcessedTimeStamp: 2026 09 01  03 48 41
%ProcessingTool: "WaveModelFilter" 4.0.4
%ProcessingTool: "SpectraToWavesModel" 11.10.0
%ProcessingTool: "WaveModelForFive" 11.8.0
%ProcessingTool: "WaveModelArchiver" 13.2.1
%ProcessingTool: "AnalyzeSpectra" 12.0.0
%End:
