%CTF: 1.00
%FileType: WVMD WVM9 "Wave History"
%UUID: 6750AEB8-1893-4DDB-B1C5-152349321AE5
%Manufacturer: CODAR Ocean Sensors. SeaSonde
%Site: AREN ""
%TimeMarks: start
%TimeStamp: 2026 01 01  00 00 00
%TimeZone: "UTC" +0.000 0
%Origin:  41.5775833    2.5577333
%%
%%
%% Note: Parameters for Last processed item...
%TimeCoverage: 0.250 hours
%AntennaBearing: 199.0
%RangeCells: 31
%DopplerCells: 512
%TransmitCenterFreqMHz: 13.500000
%TransmitBandwidthKHz: -90.068695
%TransmitSweepRateHz: 2.000000
%CoastlineSector: 65.0 240.0  %% Start CW to Stop in Deg NCW
%CurrentVelocityLimit: 180
%BraggSmoothingPoints: 2
%BraggHasSecondOrder: 1
%WaveBraggNoiseThreshold: 3.2
%WaveBraggPeakDropOff: 100.0
%WaveBraggPeakNull: 10.0
%WaveSplitBraggRatio: 6.30
%MaximumWavePeriod: 17.0
%WaveBearingLimits: 112.0 288.0  %% Start CW to Stop in Deg NCW
%WaveUseInnerBragg: 0  %% 0 No, 1 Yes
%WaveSecondOrderMethod: 1   %% 0/1 OnShore, 2 OffShore
%WaveSaturationRatio: 0.80
%WaveHeightLimit: 20.0
%WavePeriodSetLimit: 10.0
%PatternUUID: PatternUUID
%WaveMergeMethod: 1  %% 0 None, 1 Average, 2 Median, 3 Outlier
%WaveReductionMethod: 3  %% 0 None, 1=Temporal, 2=Spatial, 3=Both
%WaveMinDopplerPoints: 10
%WaveMinVectors: 1
%WaveMaximumWaveHeight: 1.0
%WaveMaximumWavePeriodChange: 7.00
%%
%TableType: WAVL WVM9
%TableColumns: 22
%TableColumnTypes: TIME MWHT MWPD WAVB WNDB PMWH ACNT DIST RCLL LOND LATD WDPT MTHD FLAG WHNM WHSD TYRS TMON TDAY THRS TMIN TSEC 
%TableRows: 17
%TableStart:
%%     Time     ----------Wave----------    Wind    WaveNF                                  Placement   Placement                                Height    Height                        
%%   FromStart   Height  Period   From      From    Height   Spectra   Distance   Range     Longitude    Latitude   Doppler    Wave    Vector    Valid      StdDv    Time                
%%   (seconds)     (m)     (s)   (True)    (True)     (m)     count      (km)      cell       (deg)       (deg)       bins    Method    Flag     points      (m)     Year Mo Dy  Hr Mn  S
             0      1.01   6.92   114.0    133.6      0.16      168        nan        8      0.0000000   0.0000000      11        2        0          13     0.09    2026 01 01  00 00 00
           600      1.01   6.91   114.0    134.4      0.15      168        nan        8      0.0000000   0.0000000      11        2        0          11     0.09    2026 01 01  00 10 00
          1200      1.06   7.00   114.0    131.1      0.16      168        nan        8      0.0000000   0.0000000      11        2        0          10     0.09    2026 01 01  00 20 00
          1800      1.10   7.00   114.0    129.0      0.18      168        nan        8      0.0000000   0.0000000      11        2        0          11     0.09    2026 01 01  00 30 00
          2400      1.14   6.94   114.0    132.0      0.19      168        nan        9      0.0000000   0.0000000      11        2        0          17     0.11    2026 01 01  00 40 00
          3000      1.16   6.96   114.0    131.2      0.19      168        nan        9      0.0000000   0.0000000      11        2        0          23     0.11    2026 01 01  00 50 00
          3600      1.16   6.92   114.0    126.7      0.19      168        nan        9      0.0000000   0.0000000      11        2        0          26     0.11    2026 01 01  01 00 00
          4200      1.15   6.86   114.0    123.1      0.20      168        nan        9      0.0000000   0.0000000      11        2        0          21     0.11    2026 01 01  01 10 00
          4800      1.14   6.79   114.0    130.8      0.19      168        nan        9      0.0000000   0.0000000      11        2        0          24     0.11    2026 01 01  01 20 00
          5400      1.11   6.73   114.0    129.0      0.19      168        nan        9      0.0000000   0.0000000      11        2        0          22     0.10    2026 01 01  01 30 00
          6000      1.09   6.68   114.0    125.1      0.20      168        nan        9      0.0000000   0.0000000      11        2        0          19     0.09    2026 01 01  01 40 00
          6600      1.11   6.69   114.0    122.9      0.20      168        nan        9      0.0000000   0.0000000      10        2        0          16     0.09    2026 01 01  01 50 00
          7200      1.11   6.69   114.0    123.6      0.19      168        nan        9      0.0000000   0.0000000      11        2        0          16     0.09    2026 01 01  02 00 00
          7800      1.13   6.73   114.0    129.3      0.18      168        nan        8      0.0000000   0.0000000      10        2        0          15     0.09    2026 01 01  02 10 00
          8400      1.13   6.72   114.0    129.9      0.20      168        nan       13      0.0000000   0.0000000      10        2        0          18     0.09    2026 01 01  02 20 00
          9000      1.13   6.80   114.0    122.4      0.21      168        nan       13      0.0000000   0.0000000      10        2        0          15     0.10    2026 01 01  02 30 00
          9600      1.14   6.81   114.0    127.9      0.21      168        nan       13            nan         nan      10        2        0          16     0.11    2026 01 01  02 40 00
%TableEnd:
%%
%%
%ProcessedTimeStamp: 2026 01 01  03 18 31
%ProcessingTool: "WaveModelFilter" 4.0.4
%ProcessingTool: "SpectraToWavesModel" 11.10.0
%ProcessingTool: "WaveModelForFive" 11.8.0
%ProcessingTool: "WaveModelArchiver" 13.2.1
%ProcessingTool: "AnalyzeSpectra" 12.0.0
%End:
