%CTF: 1.00
%FileType: WVMD WVM9 "Wave History"
%UUID: 4FA64E69-8208-4EFB-B2FC-8D16E781F239
%Manufacturer: CODAR Ocean Sensors. SeaSonde
%Site: CREU ""
%TimeMarks: start
%TimeStamp: 2026 06 01  00 00 00
%TimeZone: "UTC" +0.000 0
%Origin:  42.3190500    3.3158500
%%
%%
%% Note: Parameters for Last processed item...
%TimeCoverage: 0.250 hours
%AntennaBearing: 126.0
%RangeCells: 31
%DopplerCells: 512
%TransmitCenterFreqMHz: 13.500000
%TransmitBandwidthKHz: -90.068695
%TransmitSweepRateHz: 2.000000
%CoastlineSector: 310.0 200.0  %% Start CW to Stop in Deg NCW
%CurrentVelocityLimit: 150
%BraggSmoothingPoints: 1
%BraggHasSecondOrder: 1
%WaveBraggNoiseThreshold: 3.2
%WaveBraggPeakDropOff: 1000.0
%WaveBraggPeakNull: 316.2
%WaveSplitBraggRatio: 6.30
%MaximumWavePeriod: 17.0
%WaveBearingLimits: 340.0 184.0  %% Start CW to Stop in Deg NCW
%WaveUseInnerBragg: 0  %% 0 No, 1 Yes
%WaveSecondOrderMethod: 1   %% 0/1 OnShore, 2 OffShore
%WaveSaturationRatio: 0.80
%WaveHeightLimit: 20.0
%WavePeriodSetLimit: 10.0
%PatternType: 1
%PatternUUID: 90ECCAA6-0D12-4DBE-BFAF-A3726E3D650C
%WaveMergeMethod: 1  %% 0 None, 1 Average, 2 Median, 3 Outlier
%WaveReductionMethod: 3  %% 0 None, 1=Temporal, 2=Spatial, 3=Both
%WaveMinDopplerPoints: 10
%WaveMinVectors: 1
%WaveMaximumWaveHeight: 1.0
%WaveMaximumWavePeriodChange: 7.00
%%
%TableType: WAVL WVM9
%TableColumns: 22
%TableColumnTypes: TIME MWHT MWPD WAVB WNDB PMWH ACNT DIST RCLL LOND LATD WDPT MTHD FLAG WHNM WHSD TYRS TMON TDAY THRS TMIN TSEC 
%TableRows: 17
%TableStart:
%%     Time     ----------Wave----------    Wind    WaveNF                                  Placement   Placement                                Height    Height                        
%%   FromStart   Height  Period   From      From    Height   Spectra   Distance   Range     Longitude    Latitude   Doppler    Wave    Vector    Valid      StdDv    Time                
%%   (seconds)     (m)     (s)   (True)    (True)     (m)     count      (km)      cell       (deg)       (deg)       bins    Method    Flag     points      (m)     Year Mo Dy  Hr Mn  S
             0      0.41   4.21     2.7    321.1      0.16       98        nan       15      0.0000000   0.0000000      11        2        0          39     0.09    2026 06 01  00 00 00
           600      0.42   4.21     4.2    320.2      0.16       98        nan       15      0.0000000   0.0000000      11        2        0          33     0.08    2026 06 01  00 10 00
          1200      0.43   4.21     4.9    319.6      0.16       98        nan       15      0.0000000   0.0000000      11        2        0          28     0.08    2026 06 01  00 20 00
          1800      0.42   4.15     7.0    318.0      0.16       98        nan       15      0.0000000   0.0000000      11        2        0          20     0.08    2026 06 01  00 30 00
          2400      0.40   4.06     7.9    316.0      0.17       98        nan       15      0.0000000   0.0000000      11        2        0          17     0.08    2026 06 01  00 40 00
          3000      0.41   4.10     9.0    316.0      0.18       98        nan       15      0.0000000   0.0000000      11        2        0          10     0.07    2026 06 01  00 50 00
          3600      0.43   4.00    19.1    314.4      0.19       98        nan       11      0.0000000   0.0000000      12        2        0           6     0.08    2026 06 01  01 00 00
          4200      0.42   4.50     8.5    319.7      0.16       98        nan       11      0.0000000   0.0000000      11        2        0           8     0.06    2026 06 01  01 10 00
          4800      0.42   4.42     7.7    318.5      0.15       98        nan       14      0.0000000   0.0000000      11        2        0          12     0.09    2026 06 01  01 20 00
          5400      0.39   4.26     4.2    319.2      0.15       98        nan       14      0.0000000   0.0000000      11        2        0          19     0.08    2026 06 01  01 30 00
          6000      0.40   4.19     3.0    319.7      0.14       98        nan       14      0.0000000   0.0000000      11        2        0          27     0.08    2026 06 01  01 40 00
          6600      0.40   4.19     3.2    320.2      0.13       98        nan       15      0.0000000   0.0000000      12        2        0          36     0.08    2026 06 01  01 50 00
          7200      0.42   4.13     3.0    319.6      0.13       98        nan       15      0.0000000   0.0000000      12        2        0          45     0.08    2026 06 01  02 00 00
          7800      0.42   4.12     2.6    319.8      0.12       98        nan       15      0.0000000   0.0000000      12        2        0          52     0.07    2026 06 01  02 10 00
          8400      0.43   4.07     3.8    319.4      0.12       98        nan       15      0.0000000   0.0000000      12        2        0          56     0.07    2026 06 01  02 20 00
          9000      0.44   4.10     3.0    319.4      0.12       98        nan       15      0.0000000   0.0000000      12        2        0          62     0.07    2026 06 01  02 30 00
          9600      0.47   4.11     3.8    318.9      0.11       98        nan       15            nan         nan      13        2        0          62     0.07    2026 06 01  02 40 00
%TableEnd:
%%
%%
%ProcessedTimeStamp: 2026 06 01  03 19 27
%ProcessingTool: "WaveModelFilter" 4.0.4
%ProcessingTool: "SpectraToWavesModel" 11.10.0
%ProcessingTool: "WaveModelForFive" 11.8.0
%ProcessingTool: "WaveModelArchiver" 13.2.1
%ProcessingTool: "AnalyzeSpectra" 12.0.0
%End:
