%CTF: 1.00
%FileType: WVMD WVM9 "Wave History"
%UUID: E219C0A4-31CF-429E-9209-25F10E4EAAF0
%Manufacturer: CODAR Ocean Sensors. SeaSonde
%Site: CREU ""
%TimeMarks: start
%TimeStamp: 2024 11 01  00 00 00
%TimeZone: "UTC" +0.000 0
%Origin:  42.3190500    3.3158500
%%
%%
%% Note: Parameters for Last processed item...
%TimeCoverage: 0.250 hours
%AntennaBearing: 126.0
%RangeCells: 31
%DopplerCells: 512
%TransmitCenterFreqMHz: 13.500000
%TransmitBandwidthKHz: -90.068695
%TransmitSweepRateHz: 2.000000
%CoastlineSector: 310.0 200.0  %% Start CW to Stop in Deg NCW
%CurrentVelocityLimit: 150
%BraggSmoothingPoints: 1
%BraggHasSecondOrder: 1
%WaveBraggNoiseThreshold: 3.2
%WaveBraggPeakDropOff: 1000.0
%WaveBraggPeakNull: 316.2
%WaveSplitBraggRatio: 6.30
%MaximumWavePeriod: 17.0
%WaveBearingLimits: 340.0 184.0  %% Start CW to Stop in Deg NCW
%WaveUseInnerBragg: 0  %% 0 No, 1 Yes
%WaveSecondOrderMethod: 1   %% 0/1 OnShore, 2 OffShore
%WaveSaturationRatio: 0.80
%WaveHeightLimit: 20.0
%WavePeriodSetLimit: 10.0
%PatternType: 1
%PatternUUID: 79408457-2BE0-4066-A47D-CB7ABF326C25
%WaveMergeMethod: 1  %% 0 None, 1 Average, 2 Median, 3 Outlier
%WaveReductionMethod: 3  %% 0 None, 1=Temporal, 2=Spatial, 3=Both
%WaveMinDopplerPoints: 10
%WaveMinVectors: 1
%WaveMaximumWaveHeight: 1.0
%WaveMaximumWavePeriodChange: 7.00
%%
%TableType: WAVL WVM9
%TableColumns: 22
%TableColumnTypes: TIME MWHT MWPD WAVB WNDB PMWH ACNT DIST RCLL LOND LATD WDPT MTHD FLAG WHNM WHSD TYRS TMON TDAY THRS TMIN TSEC 
%TableRows: 20
%TableStart:
%%     Time     ----------Wave----------    Wind    WaveNF                                  Placement   Placement                                Height    Height                        
%%   FromStart   Height  Period   From      From    Height   Spectra   Distance   Range     Longitude    Latitude   Doppler    Wave    Vector    Valid      StdDv    Time                
%%   (seconds)     (m)     (s)   (True)    (True)     (m)     count      (km)      cell       (deg)       (deg)       bins    Method    Flag     points      (m)     Year Mo Dy  Hr Mn  S
             0      0.57   4.56   170.5    120.8      0.12       98        nan       15      0.0000000   0.0000000      13        2        0          25     0.11    2024 11 01  00 00 00
           600      0.53   4.46   158.3    122.3      0.11       98        nan       15      0.0000000   0.0000000      14        2        0          24     0.12    2024 11 01  00 10 00
          1200      0.47   4.25   138.5    123.0      0.10       98        nan       11      0.0000000   0.0000000      14        2        0          20     0.11    2024 11 01  00 20 00
          1800      0.43   4.12   116.4    123.7      0.10       98        nan       11      0.0000000   0.0000000      14        2        0          17     0.07    2024 11 01  00 30 00
          2400      0.43   4.11   111.6    124.3      0.10       98        nan       11      0.0000000   0.0000000      14        2        0          18     0.07    2024 11 01  00 40 00
          3000      0.42   4.18    99.7    124.3      0.11       98        nan       11      0.0000000   0.0000000      14        2        0          17     0.06    2024 11 01  00 50 00
          3600      0.43   4.17    92.6    125.5      0.11       98        nan       11      0.0000000   0.0000000      14        2        0          18     0.06    2024 11 01  01 00 00
          4200      0.43   4.18    72.9    119.1      0.12       98        nan       12      0.0000000   0.0000000      13        2        0          17     0.06    2024 11 01  01 10 00
          4800      0.44   4.14    72.9    115.3      0.13       98        nan       12      0.0000000   0.0000000      13        2        0          14     0.05    2024 11 01  01 20 00
          5400      0.45   4.18    70.7    109.3      0.13       98        nan       12      0.0000000   0.0000000      13        2        0          11     0.04    2024 11 01  01 30 00
          6000      0.46   4.18    74.9    107.5      0.13       98        nan       12      0.0000000   0.0000000      13        2        0          11     0.06    2024 11 01  01 40 00
          6600      0.47   4.15    65.3     21.0      0.13       98        nan       12      0.0000000   0.0000000      13        2        0          13     0.06    2024 11 01  01 50 00
          7200      0.46   3.93    65.6    354.6      0.12       98        nan       12      0.0000000   0.0000000      13        2        0          15     0.06    2024 11 01  02 00 00
          7800      0.48   4.00    64.5      0.3      0.12       98        nan       12      0.0000000   0.0000000      13        2        0          15     0.06    2024 11 01  02 10 00
          8400      0.49   4.00    61.8     14.2      0.12       98        nan       12      0.0000000   0.0000000      12        2        0          11     0.07    2024 11 01  02 20 00
          9000      0.48   3.90    59.4    338.1      0.12       98        nan       10      0.0000000   0.0000000      12        2        0          10     0.05    2024 11 01  02 30 00
          9600      0.46   4.00    60.8     37.9      0.12       98        nan       15      0.0000000   0.0000000      12        2        0          14     0.06    2024 11 01  02 40 00
         10200      0.46   4.06    56.5     80.6      0.12       98        nan       15      0.0000000   0.0000000      13        2        0          17     0.07    2024 11 01  02 50 00
         10800      0.45   4.33    51.9    114.8      0.12       98        nan       15      0.0000000   0.0000000      13        2        0          12     0.07    2024 11 01  03 00 00
         11400      0.47   4.38    50.2    117.8      0.12       98        nan       15            nan         nan      14        2        0          13     0.07    2024 11 01  03 10 00
%TableEnd:
%%
%%
%ProcessedTimeStamp: 2024 11 01  03 49 03
%ProcessingTool: "WaveModelFilter" 4.0.4
%ProcessingTool: "SpectraToWavesModel" 11.10.0
%ProcessingTool: "WaveModelForFive" 11.8.0
%ProcessingTool: "WaveModelArchiver" 13.2.1
%ProcessingTool: "AnalyzeSpectra" 12.0.0
%End:
