%CTF: 1.00
%FileType: WVMD WVM9 "Wave History"
%UUID: 2F3793AF-FF7E-4F2F-89D3-D9150D43B8D1
%Manufacturer: CODAR Ocean Sensors. SeaSonde
%Site: CREU ""
%TimeMarks: start
%TimeStamp: 2026 08 01  00 00 00
%TimeZone: "UTC" +0.000 0
%Origin:  42.3190500    3.3158500
%%
%%
%% Note: Parameters for Last processed item...
%TimeCoverage: 0.250 hours
%AntennaBearing: 126.0
%RangeCells: 31
%DopplerCells: 512
%TransmitCenterFreqMHz: 13.500000
%TransmitBandwidthKHz: -90.068695
%TransmitSweepRateHz: 2.000000
%CoastlineSector: 310.0 200.0  %% Start CW to Stop in Deg NCW
%CurrentVelocityLimit: 150
%BraggSmoothingPoints: 1
%BraggHasSecondOrder: 1
%WaveBraggNoiseThreshold: 3.2
%WaveBraggPeakDropOff: 1000.0
%WaveBraggPeakNull: 316.2
%WaveSplitBraggRatio: 6.30
%MaximumWavePeriod: 17.0
%WaveBearingLimits: 340.0 184.0  %% Start CW to Stop in Deg NCW
%WaveUseInnerBragg: 0  %% 0 No, 1 Yes
%WaveSecondOrderMethod: 1   %% 0/1 OnShore, 2 OffShore
%WaveSaturationRatio: 0.80
%WaveHeightLimit: 20.0
%WavePeriodSetLimit: 10.0
%PatternType: 1
%PatternUUID: 90ECCAA6-0D12-4DBE-BFAF-A3726E3D650C
%WaveMergeMethod: 1  %% 0 None, 1 Average, 2 Median, 3 Outlier
%WaveReductionMethod: 3  %% 0 None, 1=Temporal, 2=Spatial, 3=Both
%WaveMinDopplerPoints: 10
%WaveMinVectors: 1
%WaveMaximumWaveHeight: 1.0
%WaveMaximumWavePeriodChange: 7.00
%%
%TableType: WAVL WVM9
%TableColumns: 22
%TableColumnTypes: TIME MWHT MWPD WAVB WNDB PMWH ACNT DIST RCLL LOND LATD WDPT MTHD FLAG WHNM WHSD TYRS TMON TDAY THRS TMIN TSEC 
%TableRows: 20
%TableStart:
%%     Time     ----------Wave----------    Wind    WaveNF                                  Placement   Placement                                Height    Height                        
%%   FromStart   Height  Period   From      From    Height   Spectra   Distance   Range     Longitude    Latitude   Doppler    Wave    Vector    Valid      StdDv    Time                
%%   (seconds)     (m)     (s)   (True)    (True)     (m)     count      (km)      cell       (deg)       (deg)       bins    Method    Flag     points      (m)     Year Mo Dy  Hr Mn  S
             0      1.51  10.75   341.0    321.0      0.19       98        nan       14      0.0000000   0.0000000      21        2        0           4     0.09    2026 08 01  00 00 00
           600      1.51  10.75   341.0    321.0      0.19       98        nan       14      0.0000000   0.0000000      21        2        0           4     0.09    2026 08 01  00 10 00
          1200      1.51  10.75   341.0    321.0      0.19       98        nan       14      0.0000000   0.0000000      21        2        0           4     0.09    2026 08 01  00 20 00
          1800      1.20  11.00   341.0    316.0      0.22       98        nan       12      0.0000000   0.0000000      16        2        0           2     0.02    2026 08 01  00 30 00
          2400      1.18  11.00   341.0    316.0      0.24       98        nan       12      0.0000000   0.0000000      14        2        0           1     0.00    2026 08 01  00 40 00
          3000    999.00 999.00     0.0    317.2      0.18       98        nan        2      0.0000000   0.0000000       4        2      496           0     0.00    2026 08 01  00 50 00
          3600    999.00 999.00     0.0    316.2      0.19       98        nan        2      0.0000000   0.0000000       6        2      496           0     0.00    2026 08 01  01 00 00
          4200    999.00 999.00     0.0    315.1      0.19       98        nan        2      0.0000000   0.0000000       8        2      464           0     0.00    2026 08 01  01 10 00
          4800    999.00 999.00     0.0    314.4      0.19       98        nan        2      0.0000000   0.0000000      10        2      464           0     0.00    2026 08 01  01 20 00
          5400      1.48   6.00   146.0    306.0      0.18       98        nan       10      0.0000000   0.0000000      15        2        0           2     0.45    2026 08 01  01 30 00
          6000      1.02   6.00   151.0    306.0      0.16       98        nan       10      0.0000000   0.0000000      13        2        0           1     0.00    2026 08 01  01 40 00
          6600      1.02   6.00   151.0    306.0      0.16       98        nan       10      0.0000000   0.0000000      13        2        0           1     0.00    2026 08 01  01 50 00
          7200    999.00 999.00     0.0    315.2      0.16       98        nan        2      0.0000000   0.0000000      11        2      464           0     0.00    2026 08 01  02 00 00
          7800      1.02   6.00   151.0    306.0      0.16       98        nan       10      0.0000000   0.0000000      13        2        0           1     0.00    2026 08 01  02 10 00
          8400    999.00 999.00     0.0    315.9      0.13       98        nan        2      0.0000000   0.0000000       8        2      464           0     0.00    2026 08 01  02 20 00
          9000    999.00 999.00     0.0    316.2      0.12       98        nan        2      0.0000000   0.0000000       7        2      336           0     0.00    2026 08 01  02 30 00
          9600    999.00 999.00     0.0    316.4      0.11       98        nan        2      0.0000000   0.0000000       8        2      336           0     0.00    2026 08 01  02 40 00
         10200    999.00 999.00     0.0    316.0      0.10       98        nan        2      0.0000000   0.0000000       8        2      336           0     0.00    2026 08 01  02 50 00
         10800      0.54   4.00     1.0    314.3      0.11       98        nan       15      0.0000000   0.0000000      11        2        0           6     0.15    2026 08 01  03 00 00
         11400      0.40   4.00   353.9    316.0      0.09       98        nan       15            nan         nan      12        2        0          24     0.07    2026 08 01  03 10 00
%TableEnd:
%%
%%
%ProcessedTimeStamp: 2026 08 01  03 49 22
%ProcessingTool: "WaveModelFilter" 4.0.4
%ProcessingTool: "SpectraToWavesModel" 11.10.0
%ProcessingTool: "WaveModelForFive" 11.8.0
%ProcessingTool: "WaveModelArchiver" 13.2.1
%ProcessingTool: "AnalyzeSpectra" 12.0.0
%End:
