%CTF: 1.00
%FileType: WVMD WVM9 "Wave History"
%UUID: 3DBF699A-55FF-4A10-A350-8EFD884D0E00
%Manufacturer: CODAR Ocean Sensors. SeaSonde
%Site: CREU ""
%TimeMarks: start
%TimeStamp: 2024 12 01  00 00 00
%TimeZone: "UTC" +0.000 0
%Origin:  42.3190500    3.3158500
%%
%%
%% Note: Parameters for Last processed item...
%TimeCoverage: 0.250 hours
%AntennaBearing: 126.0
%RangeCells: 31
%DopplerCells: 512
%TransmitCenterFreqMHz: 13.500000
%TransmitBandwidthKHz: -90.068695
%TransmitSweepRateHz: 2.000000
%CoastlineSector: 310.0 200.0  %% Start CW to Stop in Deg NCW
%CurrentVelocityLimit: 150
%BraggSmoothingPoints: 1
%BraggHasSecondOrder: 1
%WaveBraggNoiseThreshold: 3.2
%WaveBraggPeakDropOff: 1000.0
%WaveBraggPeakNull: 316.2
%WaveSplitBraggRatio: 6.30
%MaximumWavePeriod: 17.0
%WaveBearingLimits: 340.0 184.0  %% Start CW to Stop in Deg NCW
%WaveUseInnerBragg: 0  %% 0 No, 1 Yes
%WaveSecondOrderMethod: 1   %% 0/1 OnShore, 2 OffShore
%WaveSaturationRatio: 0.80
%WaveHeightLimit: 20.0
%WavePeriodSetLimit: 10.0
%PatternType: 1
%PatternUUID: 79408457-2BE0-4066-A47D-CB7ABF326C25
%WaveMergeMethod: 1  %% 0 None, 1 Average, 2 Median, 3 Outlier
%WaveReductionMethod: 3  %% 0 None, 1=Temporal, 2=Spatial, 3=Both
%WaveMinDopplerPoints: 10
%WaveMinVectors: 1
%WaveMaximumWaveHeight: 1.0
%WaveMaximumWavePeriodChange: 7.00
%%
%TableType: WAVL WVM9
%TableColumns: 22
%TableColumnTypes: TIME MWHT MWPD WAVB WNDB PMWH ACNT DIST RCLL LOND LATD WDPT MTHD FLAG WHNM WHSD TYRS TMON TDAY THRS TMIN TSEC 
%TableRows: 24
%TableStart:
%%     Time     ----------Wave----------    Wind    WaveNF                                  Placement   Placement                                Height    Height                        
%%   FromStart   Height  Period   From      From    Height   Spectra   Distance   Range     Longitude    Latitude   Doppler    Wave    Vector    Valid      StdDv    Time                
%%   (seconds)     (m)     (s)   (True)    (True)     (m)     count      (km)      cell       (deg)       (deg)       bins    Method    Flag     points      (m)     Year Mo Dy  Hr Mn  S
             0      0.73   6.00    39.7    116.0      0.12       98        nan        7      0.0000000   0.0000000      10        2        0           4     0.02    2024 12 01  00 00 00
           600      0.74   6.00    36.8    116.0      0.12       98        nan        7      0.0000000   0.0000000      10        2        0           8     0.05    2024 12 01  00 10 00
          1200      0.72   6.10    44.5    116.0      0.12       98        nan        7      0.0000000   0.0000000      11        2        0          10     0.09    2024 12 01  00 20 00
          1800      0.72   6.10    44.5    116.0      0.12       98        nan        7      0.0000000   0.0000000      11        2        0          10     0.09    2024 12 01  00 30 00
          2400      0.71   6.09    44.1    116.9      0.12       98        nan        7      0.0000000   0.0000000      10        2        0          11     0.09    2024 12 01  00 40 00
          3000      0.71   6.10    45.6    117.0      0.12       98        nan        7      0.0000000   0.0000000      11        2        0          10     0.10    2024 12 01  00 50 00
          3600      0.67   6.09    49.1    117.8      0.12       98        nan        7      0.0000000   0.0000000      10        2        0          11     0.12    2024 12 01  01 00 00
          4200      0.62   6.00    50.3    118.5      0.11       98        nan        6      0.0000000   0.0000000      11        2        0           8     0.11    2024 12 01  01 10 00
          4800      0.57   6.00    56.0    121.0      0.11       98        nan        5      0.0000000   0.0000000      10        2        0           6     0.06    2024 12 01  01 20 00
          5400      0.55   6.00    54.9    122.0      0.11       98        nan        5      0.0000000   0.0000000      10        2        0           5     0.07    2024 12 01  01 30 00
          6000      0.55   6.00    57.7    121.0      0.11       98        nan        5      0.0000000   0.0000000      10        2        0           6     0.07    2024 12 01  01 40 00
          6600      0.54   6.00    61.0    120.0      0.11       98        nan        5      0.0000000   0.0000000      10        2        0           5     0.07    2024 12 01  01 50 00
          7200      0.54   6.00    61.0    120.0      0.11       98        nan        5      0.0000000   0.0000000      10        2        0           5     0.07    2024 12 01  02 00 00
          7800      0.57   6.00    64.4    119.3      0.11       98        nan        5      0.0000000   0.0000000      10        2        0           3     0.07    2024 12 01  02 10 00
          8400      0.55   6.20    70.0    114.0      0.11       98        nan        6      0.0000000   0.0000000      10        2        0           5     0.11    2024 12 01  02 20 00
          9000      0.52   6.20    70.0    112.0      0.11       98        nan        6      0.0000000   0.0000000      10        2        0           5     0.10    2024 12 01  02 30 00
          9600      0.53   6.25    68.4    111.0      0.11       98        nan        6      0.0000000   0.0000000      10        2        0           4     0.11    2024 12 01  02 40 00
         10200      0.54   6.50    72.3    108.5      0.11       98        nan        6      0.0000000   0.0000000      10        2        0           4     0.11    2024 12 01  02 50 00
         10800      0.54   6.50    72.3    108.5      0.11       98        nan        6      0.0000000   0.0000000      10        2        0           4     0.11    2024 12 01  03 00 00
         11400      0.54   6.50    72.3    108.5      0.11       98        nan        6      0.0000000   0.0000000      10        2        0           4     0.11    2024 12 01  03 10 00
         12000      0.54   6.50    72.3    108.5      0.11       98        nan        6      0.0000000   0.0000000      10        2        0           4     0.11    2024 12 01  03 20 00
         12600      0.57   6.67    66.0    112.7      0.11       98        nan        5      0.0000000   0.0000000      11        2        0           3     0.05    2024 12 01  03 30 00
         13200      0.60   6.80    88.6    110.0      0.12       98        nan        9      0.0000000   0.0000000      11        2        0           5     0.08    2024 12 01  03 40 00
         13800      0.59   6.83    83.9    111.0      0.12       98        nan        9            nan         nan      11        2        0           6     0.08    2024 12 01  03 50 00
%TableEnd:
%%
%%
%ProcessedTimeStamp: 2024 12 01  04 31 47
%ProcessingTool: "WaveModelFilter" 4.0.4
%ProcessingTool: "SpectraToWavesModel" 11.10.0
%ProcessingTool: "WaveModelForFive" 11.8.0
%ProcessingTool: "WaveModelArchiver" 13.2.1
%ProcessingTool: "AnalyzeSpectra" 12.0.0
%End:
