%CTF: 1.00
%FileType: WVMD WVMT "Wave History"
%UUID: AD5705E6-D505-4A69-8408-AF6BA9D96584
%Manufacturer: CODAR Ocean Sensors. SeaSonde
%Site: SCAL ""
%TimeMarks: start
%TimeStamp: 2026 05 01  00 00 00
%TimeZone: "UTC" +0.000 0 "Atlantic/Reykjavik"
%Origin:  41.1862833    1.6073000
%%
%%
%% Note: Parameters for Last processed item...
%TimeCoverage: 0.250 hours
%RangeResolutionKMeters: 1.66424 km
%AntennaBearing: 217.0
%RangeCells: 31
%DopplerCells: 512
%TransmitCenterFreqMHz: 13.500000
%TransmitBandwidthKHz: -90.068695
%TransmitSweepRateHz: 2.000000
%CoastlineSector: 75.0 250.0  %% Start CW to Stop in Deg NCW
%CurrentVelocityLimit: 180
%BraggSmoothingPoints: 4
%WaveBraggNoiseThreshold: 3.2
%WaveBraggPeakDropOff: 80.0
%WaveBraggPeakNull: 10.0
%WaveSplitBraggRatio: 2.00
%MaximumWavePeriod: 17.0
%WaveBearingLimits: 78.0 252.0  %% Start CW to Stop in Deg NCW
%WaveUseInnerBragg: 0  %% 0 No, 1 Yes
%WaveSecondOrderMethod: 1   %% 0/1 OnShore, 2 OffShore
%WaveSaturationRatio: 0.80
%WaveHeightLimit: 20.0
%WavePeriodSetLimit: 10.0
%WaveMergeMethod: 1  %% 0 None, 1 Average, 2 Median, 3 Outlier
%WaveReductionMethod: 3  %% 0 None, 1=Temporal, 2=Spatial, 3=Both
%WaveMinDopplerPoints: 10
%WaveMinVectors: 1
%WaveMaximumWaveHeight: 10.0
%WaveMaximumWaveHeightChange: 1.00
%WaveMaximumWavePeriodChange: 7.00
%%
%TableType: WAVL WVMT
%TableColumns: 22
%TableColumnTypes: TIME MWHT MWPD WAVB WNDB PMWH ACNT DIST RCLL LOND LATD WDPT MTHD FLAG WHNM WHSD TYRS TMON TDAY THRS TMIN TSEC 
%TableRows: 17
%TableStart:
%%     Time     ----------Wave----------    Wind    WaveNF                                  Placement   Placement                                Height    Height                        
%%   FromStart   Height  Period   From      From    Height   Spectra   Distance   Range     Longitude    Latitude   Doppler    Wave    Vector    Valid      StdDv    Time                
%%   (seconds)     (m)     (s)   (True)    (True)     (m)     count      (km)      cell       (deg)       (deg)       bins    Method    Flag     points      (m)     Year Mo Dy  Hr Mn  S
             0    999.00 999.00     0.0    145.0      0.37       98        nan        2      1.6579087  41.0647902       4        2       16           0     0.00    2026 05 01  00 00 00
           600    999.00 999.00     0.0    144.2      0.36       98        nan        2      1.6579087  41.0647902       4        2       16           0     0.00    2026 05 01  00 10 00
          1200    999.00 999.00     0.0    144.2      0.36       98        nan        2      1.6579087  41.0647902       4        2       16           0     0.00    2026 05 01  00 20 00
          1800      1.40   5.00   137.0    147.0      0.29        1        nan        3      1.6579087  41.0647902      10        2     1040           1     0.00    2026 05 01  00 30 00
          2400      1.25   6.00   147.0    147.0      0.39        1        nan        9      1.6579087  41.0647902      13        2     1024           1     0.00    2026 05 01  00 40 00
          3000      1.26   6.00   152.0    149.5      0.34        4        nan        9      1.6579087  41.0647902      14        2     1024           4     0.09    2026 05 01  00 50 00
          3600      1.24   6.00   151.4    149.5      0.32        8        nan        9      1.6579087  41.0647902      14        2     1024           8     0.08    2026 05 01  01 00 00
          4200      1.25   6.00   149.8    149.2      0.33        9        nan        9      1.6579087  41.0647902      14        2     1024           9     0.09    2026 05 01  01 10 00
          4800      1.25   6.00   149.8    149.2      0.33        9        nan        9      1.6579087  41.0647902      14        2     1040           9     0.09    2026 05 01  01 20 00
          5400      1.25   6.00   149.8    149.2      0.33        9        nan        9      1.6579087  41.0647902      14        2        0           9     0.09    2026 05 01  01 30 00
          6000      1.21   6.00   150.5    148.5      0.30       13        nan        9      1.6579087  41.0647902      15        2        0          13     0.10    2026 05 01  01 40 00
          6600      1.21   6.00   149.0    148.0      0.29       10        nan        9      1.6579087  41.0647902      15        2        0          10     0.09    2026 05 01  01 50 00
          7200      1.21   6.00   148.7    147.0      0.28        9        nan        9      1.6579087  41.0647902      15        2        0           9     0.09    2026 05 01  02 00 00
          7800      1.20   6.00   147.0    145.0      0.27        5        nan        9      1.6579087  41.0647902      16        2        0           5     0.11    2026 05 01  02 10 00
          8400      1.19   6.00   145.3    143.7      0.23        3        nan        4      1.6579087  41.0647902      15        2        0           3     0.08    2026 05 01  02 20 00
          9000      1.19   6.00   145.3    143.7      0.23        3        nan        4      1.6579087  41.0647902      15        2        0           3     0.08    2026 05 01  02 30 00
          9600      1.19   6.00   145.3    143.7      0.23        3        nan        4      1.6579087  41.0647902      15        2        0           3     0.08    2026 05 01  02 40 00
%TableEnd:
%%
%%
%ProcessedTimeStamp: 2026 05 01  03 17 57
%ProcessingTool: "SpectraToWavesModel" 11.10.0
%ProcessingTool: "WaveModelForFive" 11.8.1
%ProcessingTool: "WaveModelFilter" 5.1.9
%ProcessingTool: "WaveModelArchiver" 14.0.6
%ProcessingTool: "AnalyzeSpectra" 12.1.0
%End:
