%CTF: 1.00
%FileType: WVMD WVM9 "Wave History"
%UUID: A381F31B-E33E-410E-B41D-FE86ECE5F10C
%Manufacturer: CODAR Ocean Sensors. SeaSonde
%Site: BEGU ""
%TimeMarks: start
%TimeStamp: 2025 10 01  00 00 00
%TimeZone: "UTC" +0.000 0
%Origin:  41.9671667    3.2305333
%%
%%
%% Note: Parameters for Last processed item...
%TimeCoverage: 0.250 hours
%AntennaBearing: 132.0
%RangeCells: 31
%DopplerCells: 512
%TransmitCenterFreqMHz: 13.500000
%TransmitBandwidthKHz: -90.068695
%TransmitSweepRateHz: 2.000000
%CoastlineSector: 345.0 175.0  %% Start CW to Stop in Deg NCW
%CurrentVelocityLimit: 150
%BraggSmoothingPoints: 3
%BraggHasSecondOrder: 1
%WaveBraggNoiseThreshold: 3.2
%WaveBraggPeakDropOff: 1000.0
%WaveBraggPeakNull: 316.2
%WaveSplitBraggRatio: 6.30
%MaximumWavePeriod: 17.0
%WaveBearingLimits: 345.0 175.0  %% Start CW to Stop in Deg NCW
%WaveUseInnerBragg: 0  %% 0 No, 1 Yes
%WaveSecondOrderMethod: 1   %% 0/1 OnShore, 2 OffShore
%WaveSaturationRatio: 0.80
%WaveHeightLimit: 20.0
%WavePeriodSetLimit: 10.0
%PatternType: 1
%PatternUUID: CEE17C0B-1B01-4A50-94D2-D0FC2654E743
%WaveMergeMethod: 1  %% 0 None, 1 Average, 2 Median, 3 Outlier
%WaveReductionMethod: 3  %% 0 None, 1=Temporal, 2=Spatial, 3=Both
%WaveMinDopplerPoints: 10
%WaveMinVectors: 1
%WaveMaximumWaveHeight: 1.0
%WaveMaximumWavePeriodChange: 7.00
%%
%TableType: WAVL WVM9
%TableColumns: 22
%TableColumnTypes: TIME MWHT MWPD WAVB WNDB PMWH ACNT DIST RCLL LOND LATD WDPT MTHD FLAG WHNM WHSD TYRS TMON TDAY THRS TMIN TSEC 
%TableRows: 19
%TableStart:
%%     Time     ----------Wave----------    Wind    WaveNF                                  Placement   Placement                                Height    Height                        
%%   FromStart   Height  Period   From      From    Height   Spectra   Distance   Range     Longitude    Latitude   Doppler    Wave    Vector    Valid      StdDv    Time                
%%   (seconds)     (m)     (s)   (True)    (True)     (m)     count      (km)      cell       (deg)       (deg)       bins    Method    Flag     points      (m)     Year Mo Dy  Hr Mn  S
             0      0.85   4.27   103.6     42.7      0.04       98        nan       13      0.0000000   0.0000000      20        2        0          15     0.10    2025 10 01  00 00 00
           600      0.88   4.24   101.9     43.2      0.05       98        nan       13      0.0000000   0.0000000      19        2        0          17     0.11    2025 10 01  00 10 00
          1200      0.95   4.45    98.2     42.9      0.05       98        nan       13      0.0000000   0.0000000      18        2        0          22     0.11    2025 10 01  00 20 00
          1800      0.99   4.65    97.9     43.0      0.05       98        nan       14      0.0000000   0.0000000      18        2        0          31     0.11    2025 10 01  00 30 00
          2400      1.01   4.68    96.4     42.6      0.05       98        nan       14      0.0000000   0.0000000      18        2        0          34     0.11    2025 10 01  00 40 00
          3000      1.01   4.71    95.8     42.9      0.05       98        nan       14      0.0000000   0.0000000      19        2        0          35     0.11    2025 10 01  00 50 00
          3600      1.03   4.74    96.5     43.0      0.05       98        nan       14      0.0000000   0.0000000      18        2        0          31     0.07    2025 10 01  01 00 00
          4200      1.04   4.77    95.6     43.3      0.05       98        nan       14      0.0000000   0.0000000      19        2        0          31     0.08    2025 10 01  01 10 00
          4800      1.06   4.77    97.8     43.6      0.05       98        nan       14      0.0000000   0.0000000      18        2        0          31     0.08    2025 10 01  01 20 00
          5400      1.08   4.77   100.4     43.7      0.05       98        nan       14      0.0000000   0.0000000      19        2        0          30     0.10    2025 10 01  01 30 00
          6000      1.10   4.74   102.5     43.8      0.05       98        nan       14      0.0000000   0.0000000      19        2        0          27     0.09    2025 10 01  01 40 00
          6600      1.12   4.79   103.9     45.3      0.05       98        nan       15      0.0000000   0.0000000      18        2        0          33     0.09    2025 10 01  01 50 00
          7200      1.13   4.81   105.5     46.2      0.05       98        nan       15      0.0000000   0.0000000      17        2        0          31     0.09    2025 10 01  02 00 00
          7800      1.14   4.82   105.2     45.8      0.05       98        nan       15      0.0000000   0.0000000      17        2        0          39     0.10    2025 10 01  02 10 00
          8400      1.13   4.82   102.6     45.4      0.05       98        nan       15      0.0000000   0.0000000      17        2        0          38     0.10    2025 10 01  02 20 00
          9000      1.13   4.77   101.9     45.1      0.05       98        nan       15      0.0000000   0.0000000      18        2        0          39     0.11    2025 10 01  02 30 00
          9600      1.12   4.79   101.2     44.9      0.05       98        nan       15      0.0000000   0.0000000      18        2        0          42     0.11    2025 10 01  02 40 00
         10200      1.11   4.74    99.3     44.6      0.05       98        nan       15      0.0000000   0.0000000      19        2        0          39     0.11    2025 10 01  02 50 00
         10800      1.12   4.72    99.1     43.4      0.05       98        nan       15            nan         nan      19        2        0          36     0.11    2025 10 01  03 00 00
%TableEnd:
%%
%%
%ProcessedTimeStamp: 2025 10 01  03 39 33
%ProcessingTool: "WaveModelFilter" 4.0.4
%ProcessingTool: "SpectraToWavesModel" 11.10.0
%ProcessingTool: "WaveModelForFive" 11.8.0
%ProcessingTool: "WaveModelArchiver" 13.2.1
%ProcessingTool: "AnalyzeSpectra" 12.0.0
%End:
