%CTF: 1.00
%FileType: WVMD WVM9 "Wave History"
%UUID: 210A77BB-A9EE-42BD-A2FE-87B951C869A1
%Manufacturer: CODAR Ocean Sensors. SeaSonde
%Site: BEGU ""
%TimeMarks: start
%TimeStamp: 2026 09 01  00 00 00
%TimeZone: "UTC" +0.000 0
%Origin:  41.9671667    3.2305333
%%
%%
%% Note: Parameters for Last processed item...
%TimeCoverage: 0.250 hours
%AntennaBearing: 132.0
%RangeCells: 31
%DopplerCells: 512
%TransmitCenterFreqMHz: 13.500000
%TransmitBandwidthKHz: -90.068695
%TransmitSweepRateHz: 2.000000
%CoastlineSector: 345.0 175.0  %% Start CW to Stop in Deg NCW
%CurrentVelocityLimit: 150
%BraggSmoothingPoints: 3
%BraggHasSecondOrder: 1
%WaveBraggNoiseThreshold: 3.2
%WaveBraggPeakDropOff: 1000.0
%WaveBraggPeakNull: 316.2
%WaveSplitBraggRatio: 6.30
%MaximumWavePeriod: 17.0
%WaveBearingLimits: 345.0 175.0  %% Start CW to Stop in Deg NCW
%WaveUseInnerBragg: 0  %% 0 No, 1 Yes
%WaveSecondOrderMethod: 1   %% 0/1 OnShore, 2 OffShore
%WaveSaturationRatio: 0.80
%WaveHeightLimit: 20.0
%WavePeriodSetLimit: 10.0
%PatternType: 1
%PatternUUID: CEE17C0B-1B01-4A50-94D2-D0FC2654E743
%WaveMergeMethod: 1  %% 0 None, 1 Average, 2 Median, 3 Outlier
%WaveReductionMethod: 3  %% 0 None, 1=Temporal, 2=Spatial, 3=Both
%WaveMinDopplerPoints: 10
%WaveMinVectors: 1
%WaveMaximumWaveHeight: 1.0
%WaveMaximumWavePeriodChange: 7.00
%%
%TableType: WAVL WVM9
%TableColumns: 22
%TableColumnTypes: TIME MWHT MWPD WAVB WNDB PMWH ACNT DIST RCLL LOND LATD WDPT MTHD FLAG WHNM WHSD TYRS TMON TDAY THRS TMIN TSEC 
%TableRows: 20
%TableStart:
%%     Time     ----------Wave----------    Wind    WaveNF                                  Placement   Placement                                Height    Height                        
%%   FromStart   Height  Period   From      From    Height   Spectra   Distance   Range     Longitude    Latitude   Doppler    Wave    Vector    Valid      StdDv    Time                
%%   (seconds)     (m)     (s)   (True)    (True)     (m)     count      (km)      cell       (deg)       (deg)       bins    Method    Flag     points      (m)     Year Mo Dy  Hr Mn  S
             0      0.89   4.80    96.2     41.4      0.05       98        nan       15      0.0000000   0.0000000      15        2        0          49     0.12    2026 09 01  00 00 00
           600      0.87   4.76    98.3     41.2      0.05       98        nan       15      0.0000000   0.0000000      16        2        0          49     0.13    2026 09 01  00 10 00
          1200      0.84   4.76    99.6     41.4      0.05       98        nan       15      0.0000000   0.0000000      16        2        0          50     0.13    2026 09 01  00 20 00
          1800      0.80   4.81   100.7     42.0      0.05       98        nan       15      0.0000000   0.0000000      16        2        0          47     0.13    2026 09 01  00 30 00
          2400      0.77   4.81   100.2     42.2      0.05       98        nan       15      0.0000000   0.0000000      16        2        0          42     0.12    2026 09 01  00 40 00
          3000      0.75   4.85   101.7     42.0      0.05       98        nan       15      0.0000000   0.0000000      17        2        0          40     0.12    2026 09 01  00 50 00
          3600      0.73   4.85   101.2     42.2      0.05       98        nan       15      0.0000000   0.0000000      17        2        0          41     0.11    2026 09 01  01 00 00
          4200      0.70   4.85   102.5     41.7      0.05       98        nan       15      0.0000000   0.0000000      16        2        0          33     0.10    2026 09 01  01 10 00
          4800      0.69   4.81    98.6     42.0      0.05       98        nan       15      0.0000000   0.0000000      16        2        0          36     0.11    2026 09 01  01 20 00
          5400      0.69   4.80    98.7     41.7      0.05       98        nan       15      0.0000000   0.0000000      16        2        0          35     0.10    2026 09 01  01 30 00
          6000      0.70   4.76    96.9     41.5      0.05       98        nan       15      0.0000000   0.0000000      17        2        0          38     0.10    2026 09 01  01 40 00
          6600      0.71   4.67    92.3     41.4      0.05       98        nan       15      0.0000000   0.0000000      18        2        0          49     0.10    2026 09 01  01 50 00
          7200      0.71   4.59    90.6     41.0      0.05       98        nan       15      0.0000000   0.0000000      18        2        0          51     0.09    2026 09 01  02 00 00
          7800      0.71   4.60    90.8     40.9      0.05       98        nan       15      0.0000000   0.0000000      18        2        0          53     0.10    2026 09 01  02 10 00
          8400      0.71   4.57    90.9     40.8      0.05       98        nan       15      0.0000000   0.0000000      18        2        0          56     0.10    2026 09 01  02 20 00
          9000      0.71   4.60    89.4     40.7      0.05       98        nan       15      0.0000000   0.0000000      18        2        0          52     0.09    2026 09 01  02 30 00
          9600      0.71   4.57    88.2     40.9      0.05       98        nan       15      0.0000000   0.0000000      18        2        0          54     0.09    2026 09 01  02 40 00
         10200      0.71   4.57    89.6     41.0      0.05       98        nan       15      0.0000000   0.0000000      18        2        0          51     0.09    2026 09 01  02 50 00
         10800      0.72   4.61    93.7     41.1      0.05       98        nan       15      0.0000000   0.0000000      17        2        0          44     0.09    2026 09 01  03 00 00
         11400      0.75   4.67    98.7     41.5      0.05       98        nan       15            nan         nan      17        2        0          43     0.09    2026 09 01  03 10 00
%TableEnd:
%%
%%
%ProcessedTimeStamp: 2026 09 01  03 48 14
%ProcessingTool: "WaveModelFilter" 4.0.4
%ProcessingTool: "SpectraToWavesModel" 11.10.0
%ProcessingTool: "WaveModelForFive" 11.8.0
%ProcessingTool: "WaveModelArchiver" 13.2.1
%ProcessingTool: "AnalyzeSpectra" 12.0.0
%End:
