%CTF: 1.00
%FileType: WVMD WVM9 "Wave History"
%UUID: F1487CE9-A93F-4BFF-B8F8-7CCA32409891
%Manufacturer: CODAR Ocean Sensors. SeaSonde
%Site: BEGU ""
%TimeMarks: start
%TimeStamp: 2026 06 01  00 00 00
%TimeZone: "UTC" +0.000 0
%Origin:  41.9671667    3.2305333
%%
%%
%% Note: Parameters for Last processed item...
%TimeCoverage: 0.250 hours
%AntennaBearing: 132.0
%RangeCells: 31
%DopplerCells: 512
%TransmitCenterFreqMHz: 13.500000
%TransmitBandwidthKHz: -90.068695
%TransmitSweepRateHz: 2.000000
%CoastlineSector: 345.0 175.0  %% Start CW to Stop in Deg NCW
%CurrentVelocityLimit: 150
%BraggSmoothingPoints: 3
%BraggHasSecondOrder: 1
%WaveBraggNoiseThreshold: 3.2
%WaveBraggPeakDropOff: 1000.0
%WaveBraggPeakNull: 316.2
%WaveSplitBraggRatio: 6.30
%MaximumWavePeriod: 17.0
%WaveBearingLimits: 345.0 175.0  %% Start CW to Stop in Deg NCW
%WaveUseInnerBragg: 0  %% 0 No, 1 Yes
%WaveSecondOrderMethod: 1   %% 0/1 OnShore, 2 OffShore
%WaveSaturationRatio: 0.80
%WaveHeightLimit: 20.0
%WavePeriodSetLimit: 10.0
%PatternType: 1
%PatternUUID: CEE17C0B-1B01-4A50-94D2-D0FC2654E743
%WaveMergeMethod: 1  %% 0 None, 1 Average, 2 Median, 3 Outlier
%WaveReductionMethod: 3  %% 0 None, 1=Temporal, 2=Spatial, 3=Both
%WaveMinDopplerPoints: 10
%WaveMinVectors: 1
%WaveMaximumWaveHeight: 1.0
%WaveMaximumWavePeriodChange: 7.00
%%
%TableType: WAVL WVM9
%TableColumns: 22
%TableColumnTypes: TIME MWHT MWPD WAVB WNDB PMWH ACNT DIST RCLL LOND LATD WDPT MTHD FLAG WHNM WHSD TYRS TMON TDAY THRS TMIN TSEC 
%TableRows: 20
%TableStart:
%%     Time     ----------Wave----------    Wind    WaveNF                                  Placement   Placement                                Height    Height                        
%%   FromStart   Height  Period   From      From    Height   Spectra   Distance   Range     Longitude    Latitude   Doppler    Wave    Vector    Valid      StdDv    Time                
%%   (seconds)     (m)     (s)   (True)    (True)     (m)     count      (km)      cell       (deg)       (deg)       bins    Method    Flag     points      (m)     Year Mo Dy  Hr Mn  S
             0      1.30   4.45   126.0     42.7      0.08       98        nan       15      0.0000000   0.0000000      15        2        0          29     0.15    2026 06 01  00 00 00
           600      1.28   4.55   126.1     41.7      0.08       98        nan       15      0.0000000   0.0000000      15        2        0          31     0.15    2026 06 01  00 10 00
          1200      1.23   4.63   127.6     42.0      0.08       98        nan       15      0.0000000   0.0000000      15        2        0          32     0.15    2026 06 01  00 20 00
          1800      1.17   4.66   126.5     41.7      0.08       98        nan       15      0.0000000   0.0000000      15        2        0          29     0.14    2026 06 01  00 30 00
          2400      1.11   4.58   132.1     42.0      0.08       98        nan       15      0.0000000   0.0000000      15        2        0          26     0.11    2026 06 01  00 40 00
          3000      1.04   4.48   134.1     42.6      0.07       98        nan       15      0.0000000   0.0000000      16        2        0          31     0.11    2026 06 01  00 50 00
          3600      1.02   4.54   133.7     42.5      0.07       98        nan       15      0.0000000   0.0000000      18        2        0          37     0.11    2026 06 01  01 00 00
          4200      0.98   4.55   131.9     42.2      0.07       98        nan       15      0.0000000   0.0000000      19        2        0          40     0.12    2026 06 01  01 10 00
          4800      0.92   4.44   132.8     42.8      0.07       98        nan       15      0.0000000   0.0000000      19        2        0          39     0.12    2026 06 01  01 20 00
          5400      0.86   4.40   127.2     42.6      0.07       98        nan       15      0.0000000   0.0000000      20        2        0          35     0.11    2026 06 01  01 30 00
          6000      0.83   4.31   128.9     42.6      0.06       98        nan       15      0.0000000   0.0000000      21        2        0          35     0.10    2026 06 01  01 40 00
          6600      0.80   4.22   132.9     42.9      0.06       98        nan       15      0.0000000   0.0000000      21        2        0          32     0.09    2026 06 01  01 50 00
          7200      0.77   4.13   135.2     42.9      0.06       98        nan       15      0.0000000   0.0000000      22        2        0          32     0.10    2026 06 01  02 00 00
          7800      0.76   4.10   132.7     42.6      0.05       98        nan       15      0.0000000   0.0000000      22        2        0          31     0.09    2026 06 01  02 10 00
          8400      0.76   4.03   134.9     42.7      0.05       98        nan       12      0.0000000   0.0000000      21        2        0          30     0.09    2026 06 01  02 20 00
          9000      0.77   4.00   135.1     43.1      0.05       98        nan        9      0.0000000   0.0000000      21        2        0          27     0.09    2026 06 01  02 30 00
          9600      0.78   4.07   133.3     43.0      0.04       98        nan       12      0.0000000   0.0000000      21        2        0          30     0.10    2026 06 01  02 40 00
         10200      0.79   4.09   132.7     42.9      0.04       98        nan       12      0.0000000   0.0000000      21        2        0          33     0.11    2026 06 01  02 50 00
         10800      0.79   4.13   130.2     42.9      0.04       98        nan       12      0.0000000   0.0000000      21        2        0          32     0.11    2026 06 01  03 00 00
         11400      0.79   4.13   131.6     43.0      0.04       98        nan       12            nan         nan      20        2        0          31     0.12    2026 06 01  03 10 00
%TableEnd:
%%
%%
%ProcessedTimeStamp: 2026 06 01  03 48 07
%ProcessingTool: "WaveModelFilter" 4.0.4
%ProcessingTool: "SpectraToWavesModel" 11.10.0
%ProcessingTool: "WaveModelForFive" 11.8.0
%ProcessingTool: "WaveModelArchiver" 13.2.1
%ProcessingTool: "AnalyzeSpectra" 12.0.0
%End:
