%CTF: 1.00
%FileType: WVMD WVM9 "Wave History"
%UUID: 932339D4-EEE1-4F51-8095-CBA6CADF24F1
%Manufacturer: CODAR Ocean Sensors. SeaSonde
%Site: BEGU ""
%TimeMarks: start
%TimeStamp: 2024 04 01  00 00 00
%TimeZone: "UTC" +0.000 0
%Origin:  41.9671667    3.2305333
%%
%%
%% Note: Parameters for Last processed item...
%TimeCoverage: 0.250 hours
%AntennaBearing: 132.0
%RangeCells: 31
%DopplerCells: 512
%TransmitCenterFreqMHz: 13.500000
%TransmitBandwidthKHz: -90.068695
%TransmitSweepRateHz: 2.000000
%CoastlineSector: 345.0 175.0  %% Start CW to Stop in Deg NCW
%CurrentVelocityLimit: 150
%BraggSmoothingPoints: 3
%BraggHasSecondOrder: 1
%WaveBraggNoiseThreshold: 3.2
%WaveBraggPeakDropOff: 1000.0
%WaveBraggPeakNull: 316.2
%WaveSplitBraggRatio: 6.30
%MaximumWavePeriod: 17.0
%WaveBearingLimits: 345.0 175.0  %% Start CW to Stop in Deg NCW
%WaveUseInnerBragg: 0  %% 0 No, 1 Yes
%WaveSecondOrderMethod: 1   %% 0/1 OnShore, 2 OffShore
%WaveSaturationRatio: 0.80
%WaveHeightLimit: 20.0
%WavePeriodSetLimit: 10.0
%PatternType: 1
%PatternUUID: AD66C5A5-E020-4499-9004-ADBC03A7412D
%WaveMergeMethod: 1  %% 0 None, 1 Average, 2 Median, 3 Outlier
%WaveReductionMethod: 3  %% 0 None, 1=Temporal, 2=Spatial, 3=Both
%WaveMinDopplerPoints: 10
%WaveMinVectors: 1
%WaveMaximumWaveHeight: 1.0
%WaveMaximumWavePeriodChange: 7.00
%%
%TableType: WAVL WVM9
%TableColumns: 22
%TableColumnTypes: TIME MWHT MWPD WAVB WNDB PMWH ACNT DIST RCLL LOND LATD WDPT MTHD FLAG WHNM WHSD TYRS TMON TDAY THRS TMIN TSEC 
%TableRows: 19
%TableStart:
%%     Time     ----------Wave----------    Wind    WaveNF                                  Placement   Placement                                Height    Height                        
%%   FromStart   Height  Period   From      From    Height   Spectra   Distance   Range     Longitude    Latitude   Doppler    Wave    Vector    Valid      StdDv    Time                
%%   (seconds)     (m)     (s)   (True)    (True)     (m)     count      (km)      cell       (deg)       (deg)       bins    Method    Flag     points      (m)     Year Mo Dy  Hr Mn  S
             0      2.82   7.00    32.0    227.0      0.07       98        nan       13      0.0000000   0.0000000      26        2        0           2     0.03    2024 04 01  00 00 00
           600      2.81   7.57    39.7    226.3      0.06       98        nan       14      0.0000000   0.0000000      26        2        0           7     0.10    2024 04 01  00 10 00
          1200      2.83   7.63    39.3    227.0      0.06       98        nan       14      0.0000000   0.0000000      26        2        0           8     0.11    2024 04 01  00 20 00
          1800      2.77   7.64    33.8    227.5      0.07       98        nan       14      0.0000000   0.0000000      26        2        0          11     0.17    2024 04 01  00 30 00
          2400      2.73   7.77    39.2    225.8      0.07       98        nan       14      0.0000000   0.0000000      26        2        0          13     0.15    2024 04 01  00 40 00
          3000      2.76   7.60    27.3    225.0      0.08       98        nan       14      0.0000000   0.0000000      26        2        0          10     0.08    2024 04 01  00 50 00
          3600      2.70   7.75    32.7    225.3      0.08       98        nan       14      0.0000000   0.0000000      26        2        0          12     0.17    2024 04 01  01 00 00
          4200      2.62   7.80    29.2    226.0      0.08       98        nan       14      0.0000000   0.0000000      26        2        0          10     0.14    2024 04 01  01 10 00
          4800      2.62   7.88    33.2    225.7      0.09       98        nan       14      0.0000000   0.0000000      26        2        0           8     0.12    2024 04 01  01 20 00
          5400      2.63   7.90    34.5    227.0      0.09       98        nan       15      0.0000000   0.0000000      25        2        0          10     0.11    2024 04 01  01 30 00
          6000      2.57   7.79    34.0    227.0      0.09       98        nan       15      0.0000000   0.0000000      25        2        0          14     0.17    2024 04 01  01 40 00
          6600      2.51   8.00    37.0    230.8      0.10       98        nan       15      0.0000000   0.0000000      24        2        0           8     0.13    2024 04 01  01 50 00
          7200      2.55   8.00    37.0    230.6      0.11       98        nan       15      0.0000000   0.0000000      23        2        0           7     0.11    2024 04 01  02 00 00
          7800      2.42   7.92    39.6    229.7      0.11       98        nan       15      0.0000000   0.0000000      22        2        0          13     0.16    2024 04 01  02 10 00
          8400      2.29   7.93    39.6    230.7      0.11       98        nan       15      0.0000000   0.0000000      22        2        0          15     0.11    2024 04 01  02 20 00
          9000      2.31   7.91    36.7    229.3      0.12       98        nan       15      0.0000000   0.0000000      21        2        0          11     0.07    2024 04 01  02 30 00
          9600      2.25   7.86    35.4    229.6      0.13       98        nan       15      0.0000000   0.0000000      20        2        0          21     0.11    2024 04 01  02 40 00
         10200      2.14   7.89    33.1    229.9      0.13       98        nan       15      0.0000000   0.0000000      19        2        0          28     0.12    2024 04 01  02 50 00
         10800      2.10   7.86    31.5    229.7      0.13       98        nan       15            nan         nan      18        2        0          22     0.09    2024 04 01  03 00 00
%TableEnd:
%%
%%
%ProcessedTimeStamp: 2024 04 01  03 39 36
%ProcessingTool: "WaveModelFilter" 4.0.4
%ProcessingTool: "SpectraToWavesModel" 11.10.0
%ProcessingTool: "WaveModelForFive" 11.8.0
%ProcessingTool: "WaveModelArchiver" 13.2.1
%ProcessingTool: "AnalyzeSpectra" 12.0.0
%End:
