%CTF: 1.00
%FileType: WVMD WVM9 "Wave History"
%UUID: 5977E556-0885-44D2-8C1F-B8D257A7357A
%Manufacturer: CODAR Ocean Sensors. SeaSonde
%Site: BEGU ""
%TimeMarks: start
%TimeStamp: 2026 05 01  00 00 00
%TimeZone: "UTC" +0.000 0
%Origin:  41.9671667    3.2305333
%%
%%
%% Note: Parameters for Last processed item...
%TimeCoverage: 0.250 hours
%AntennaBearing: 132.0
%RangeCells: 31
%DopplerCells: 512
%TransmitCenterFreqMHz: 13.500000
%TransmitBandwidthKHz: -90.068695
%TransmitSweepRateHz: 2.000000
%CoastlineSector: 345.0 175.0  %% Start CW to Stop in Deg NCW
%CurrentVelocityLimit: 150
%BraggSmoothingPoints: 3
%BraggHasSecondOrder: 1
%WaveBraggNoiseThreshold: 3.2
%WaveBraggPeakDropOff: 1000.0
%WaveBraggPeakNull: 316.2
%WaveSplitBraggRatio: 6.30
%MaximumWavePeriod: 17.0
%WaveBearingLimits: 345.0 175.0  %% Start CW to Stop in Deg NCW
%WaveUseInnerBragg: 0  %% 0 No, 1 Yes
%WaveSecondOrderMethod: 1   %% 0/1 OnShore, 2 OffShore
%WaveSaturationRatio: 0.80
%WaveHeightLimit: 20.0
%WavePeriodSetLimit: 10.0
%PatternType: 1
%PatternUUID: CEE17C0B-1B01-4A50-94D2-D0FC2654E743
%WaveMergeMethod: 1  %% 0 None, 1 Average, 2 Median, 3 Outlier
%WaveReductionMethod: 3  %% 0 None, 1=Temporal, 2=Spatial, 3=Both
%WaveMinDopplerPoints: 10
%WaveMinVectors: 1
%WaveMaximumWaveHeight: 1.0
%WaveMaximumWavePeriodChange: 7.00
%%
%TableType: WAVL WVM9
%TableColumns: 22
%TableColumnTypes: TIME MWHT MWPD WAVB WNDB PMWH ACNT DIST RCLL LOND LATD WDPT MTHD FLAG WHNM WHSD TYRS TMON TDAY THRS TMIN TSEC 
%TableRows: 19
%TableStart:
%%     Time     ----------Wave----------    Wind    WaveNF                                  Placement   Placement                                Height    Height                        
%%   FromStart   Height  Period   From      From    Height   Spectra   Distance   Range     Longitude    Latitude   Doppler    Wave    Vector    Valid      StdDv    Time                
%%   (seconds)     (m)     (s)   (True)    (True)     (m)     count      (km)      cell       (deg)       (deg)       bins    Method    Flag     points      (m)     Year Mo Dy  Hr Mn  S
         49800      2.54   6.82   135.2     46.5      0.19       14        nan       15      0.0000000   0.0000000      15        2     1280          11     0.30    2026 05 01  13 50 00
         50400      2.60   6.67   138.6     45.3      0.17       28        nan       13      0.0000000   0.0000000      16        2     1280           3     0.10    2026 05 01  14 00 00
         51000      2.66   6.80   138.5     49.0      0.17       42        nan       13      0.0000000   0.0000000      16        2     1280          10     0.07    2026 05 01  14 10 00
         51600      2.50   6.79   136.3     46.1      0.16       56        nan       15      0.0000000   0.0000000      17        2     1280          29     0.16    2026 05 01  14 20 00
         52200      2.48   6.77   136.6     45.8      0.15       70        nan       15      0.0000000   0.0000000      18        2     1280          26     0.11    2026 05 01  14 30 00
         52800      2.46   6.69   138.2     45.8      0.15       84        nan       15      0.0000000   0.0000000      18        2     1280          29     0.09    2026 05 01  14 40 00
         53400      2.40   6.77   136.6     45.9      0.17       98        nan       15      0.0000000   0.0000000      17        2        0          44     0.12    2026 05 01  14 50 00
         54000      2.38   6.76   138.3     45.4      0.18       98        nan       15      0.0000000   0.0000000      17        2        0          41     0.12    2026 05 01  15 00 00
         54600      2.36   6.72   136.6     45.7      0.19       98        nan       15      0.0000000   0.0000000      17        2        0          43     0.12    2026 05 01  15 10 00
         55200      2.36   6.66   135.1     45.3      0.20       98        nan       15      0.0000000   0.0000000      17        2        0          44     0.12    2026 05 01  15 20 00
         55800      2.36   6.61   134.6     45.1      0.20       98        nan       15      0.0000000   0.0000000      17        2        0          44     0.12    2026 05 01  15 30 00
         56400      2.34   6.58   136.0     45.7      0.21       98        nan       15      0.0000000   0.0000000      17        2        0          48     0.12    2026 05 01  15 40 00
         57000      2.32   6.58   137.7     45.5      0.20       98        nan       15      0.0000000   0.0000000      17        2        0          48     0.12    2026 05 01  15 50 00
         57600      2.32   6.61   138.6     45.3      0.18       98        nan       15      0.0000000   0.0000000      17        2        0          46     0.12    2026 05 01  16 00 00
         58200      2.29   6.62   139.7     45.6      0.17       98        nan       15      0.0000000   0.0000000      18        2        0          47     0.12    2026 05 01  16 10 00
         58800      2.25   6.66   140.8     45.7      0.16       98        nan       15      0.0000000   0.0000000      17        2        0          41     0.12    2026 05 01  16 20 00
         59400      2.22   6.68   141.8     46.1      0.16       98        nan       15      0.0000000   0.0000000      17        2        0          37     0.11    2026 05 01  16 30 00
         60000      2.19   6.65   143.3     46.6      0.17       98        nan       15      0.0000000   0.0000000      16        2        0          37     0.11    2026 05 01  16 40 00
         60600      2.17   6.59   142.0     46.4      0.17       98        nan       15            nan         nan      16        2        0          34     0.12    2026 05 01  16 50 00
%TableEnd:
%%
%%
%ProcessedTimeStamp: 2026 05 01  17 29 03
%ProcessingTool: "WaveModelFilter" 4.0.4
%ProcessingTool: "SpectraToWavesModel" 11.10.0
%ProcessingTool: "WaveModelForFive" 11.8.0
%ProcessingTool: "WaveModelArchiver" 13.2.1
%ProcessingTool: "AnalyzeSpectra" 12.0.0
%End:
